files_root: .
vlnv: ::wb_intercon:0
parameters:
    masters:
      io:
        slaves: [rom, sys, spi_flash, spi_accel, ptc, gpio, vga, servo, pmod_D, dcMotor, gpio1, jstk, rgb, uart]
    slaves:
      rom:
        offset : 0x00000000
        size : 0x00001000
      sys:
        offset : 0x00001000
        size : 0x00000040
      spi_flash:
        offset : 0x00001040
        size : 0x00000040
      spi_accel:
        offset : 0x00001100
        size : 0x00000040
      ptc:
        offset : 0x00001200
        size : 0x00000040
      gpio:
        offset : 0x00001400
        size : 0x00000040
      vga:
        offset : 0x00001500
        size : 0x00000040
      servo:
        offset : 0x00001600
        size : 0x00000040
      pmod_D:
        offset : 0x00001640
        size : 0x00000040
      dcMotor:
        offset : 0x00001700
        size : 0x00000040
      gpio1:
        offset : 0x00001800
        size : 0x00000040
      jstk:
        offset : 0x00001900
        size : 0x00000040  
      rgb:
        offset : 0x00001940
        size : 0x00000040
      uart:
        offset : 0x00002000
        size : 0x00001000